### ISSUE TITLE
TypeError: Cannot read property 'message' of null

### ISSUE THREAD

**Issue by fabiusss** [scripting/xml-rpc#10]
Sometimes I get this kind of error. 
I can't manage it.

/home/ROOT/node_modules/davexmlrpc/xmlrpc.js:373
			console.log ("xmlRpcClient: err.message == " + err.message);
			                                                   ^

TypeError: Cannot read property 'message' of null
    at Request._callback (/home/ROOT/node_modules/davexmlrpc/xmlrpc.js:373:55)
    at Request.self.callback (/home/ROOT/node_modules/request/request.js:185:22)
    at Request.emit (events.js:188:13)
    at Request.<anonymous> (/home/ROOT/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:188:13)
    at IncomingMessage.<anonymous> (/home/ROOT/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:276:13)
    at IncomingMessage.emit (events.js:193:15)
    at endReadableNT (_stream_readable.js:1129:12)
    at process.internalTickCallback (internal/process/next_tick.js:72:19)

My version:
    "davexmlrpc": {
      "version": "0.4.24",
      "resolved": "https://registry.npmjs.org/davexmlrpc/-/davexmlrpc-0.4.24.tgz",
      "integrity": "sha512-u9Cy4uFRnj0+DpZYYGrPemik+Nqtj3aeHxdtDFew86kPBq93eMSJIE5/HRuM0LmGAn6JAA/ArpRBmK5ZDsTT6w==",
      "requires": {
        "davehttp": "*",
        "daveutils": "*",
        "request": "*",
        "xml2js": "*"
      }
    },

**Comment by scripting** [comment]
Thanks for the report. There was an error in the code, which I fixed. The new version is 0.4.25.
